######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 26 23:00:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/local/include/opencv
INCLUDEPATH += /usr/local/include/opencv2
LIBS += -L/usr/local/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc

# Input
SOURCES += hough.cpp
